## helper function that counts trailing spaces in a string
trailingSpaces <- function(x){
    y <- gsub("^ *", "", x)
    nchar(x)-nchar(y)
}


## This function captures the output that's generated by
## a show method for any R object and makes sure
## that lines are broken in case the output is too long
fixedWidthCat <- function(x, width=getOption("width")){
    output <-  gsub("\t", "     ", capture.output(x))
    longLines <- which(nchar(output)>width)
    for(l in longLines){
        ident <- BiocCaseStudies:::trailingSpaces(output[l])
        output[l] <- strbreak(output[l], exdent=ident, collapse="\n")
    }
    cat(output, sep="\n", collapse="")
}
